// Generated by scripts/prepare-w14-assets.mjs.
export const PROJ_ASSETS = {
  "schemaVersion": 1,
  "package": "proj-wasm",
  "version": "0.1.0-alpha9",
  "tarballSha256": "5e453ddded6fb5bebdbf89b29fd41779437a2040ac3ec9dc20c3e930774b26e2",
  "adapter": "Direct exported PROJ C API on the unmodified pinned Emscripten module in a Forge3D worker; network disabled.",
  "assets": [
    {
      "name": "proj-emscripten.js",
      "sha256": "f6e9efdfd3c916c07a98b7a743801779c3c3b2d4948b5223b5e680b4438cd8cf",
      "byteLength": 180744
    },
    {
      "name": "proj-emscripten.wasm",
      "sha256": "30347e6f3c3602e38b6d50b9539b2c7a522748d67addf312eb0d9d58104710ca",
      "byteLength": 3636337
    },
    {
      "name": "proj.db",
      "sha256": "e0203e49c386facaeb57e591101f05a6dd4d35a6fc7dad5eadd09f0e794ea14f",
      "byteLength": 10207232
    },
    {
      "name": "proj.ini",
      "sha256": "b95ebf0d007339244483d65d571cd887a51806e2bd2c1ab7f47b897d25320d65",
      "byteLength": 2435
    }
  ],
  "grids": [
    {
      "name": "us_noaa_conus.tif",
      "sha256": "44611d823c48e5347500ee6afe40ff33d2b88cf817bf59f705ed4a4c3bd687d7",
      "byteLength": 173029,
      "version": "proj-data-conus-v1",
      "source": "https://cdn.proj.org/us_noaa_conus.tif",
      "license": "Public domain (NOAA/NGS)",
      "licenseSource": "https://github.com/OSGeo/PROJ-data/blob/1.24.0/us_noaa/us_noaa_README.txt"
    }
  ],
  "notices": [
    {
      "name": "LICENSE",
      "sha256": "3e72ba12f9e61646b1d5f24f97d9b1e386bebf64f56d71817d6d4b1d6b54595c",
      "byteLength": 1083
    },
    {
      "name": "PROJ-COPYING",
      "source": "https://raw.githubusercontent.com/OSGeo/PROJ/9.8.1/COPYING",
      "sha256": "6a8f30793e877d32e3f88b972f0970a051a3b5a26cd057d3993cb51e21c43319",
      "byteLength": 1784
    },
    {
      "name": "GRID-LICENSE.txt",
      "source": "https://raw.githubusercontent.com/OSGeo/PROJ-data/1.24.0/us_noaa/us_noaa_README.txt",
      "sha256": "38561c43f20756a77d33406c54cda8c250d18b6b30bff1e00ff51578e3682723",
      "byteLength": 19653
    }
  ]
} as const;
