import './verify-w13-assets.mjs';
import { createHash } from "node:crypto";
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const repoRoot = join(root, "..", "..");
const dist = join(root, "dist");
const pkg = join(root, "pkg");

mkdirSync(dist, { recursive: true });

copyRequired(join(pkg, "forge3d_web.js"), join(dist, "forge3d_web.js"));
copyRequired(join(pkg, "forge3d_web_bg.wasm"), join(dist, "forge3d_web_bg.wasm"));
copyRequired(join(repoRoot, "LICENSE"), join(root, "LICENSE"));
copyRequired(join(repoRoot, "LICENSE-APACHE"), join(root, "LICENSE-APACHE"));

const facadePath = join(dist, "index.js");
let facade = readRequired(facadePath);
facade = facade.replace(
  "\"../pkg/forge3d_web.js\"",
  "\"./forge3d_web.js\""
);
if (facade.includes("../pkg/forge3d_web.js")) {
  throw new Error("dist/index.js still references unpublished pkg directory");
}
writeFileSync(facadePath, facade);

// ktx-parse is lock-controlled as bundled-self-hosted: ship the exact
// integrity-verified 1.1.0 module under dist/ so the package resolves it
// from 'self' without a bundler or import-map entry.
const ktxRoot = join(root, "node_modules", "ktx-parse");
const ktxVersion = JSON.parse(readRequired(join(ktxRoot, "package.json"))).version;
if (ktxVersion !== "1.1.0") {
  throw new Error(`ktx-parse must be 1.1.0 per the dependency lock, found ${ktxVersion}`);
}
const vendor = join(dist, "vendor");
mkdirSync(vendor, { recursive: true });
copyVendoredScript(join(ktxRoot, "dist", "ktx-parse.modern.js"), join(vendor, "ktx-parse.js"));
copyRequired(join(ktxRoot, "LICENSE"), join(vendor, "ktx-parse.LICENSE"));
// mediabunny is lock-controlled as bundled-self-hosted too: the exact
// integrity-verified 1.58.0 ESM bundle (MPL-2.0) is loaded lazily by video.js.
const mediabunnyRoot = join(root, "node_modules", "mediabunny");
const mediabunnyVersion = JSON.parse(readRequired(join(mediabunnyRoot, "package.json"))).version;
if (mediabunnyVersion !== "1.58.0") {
  throw new Error(`mediabunny must be 1.58.0 per the dependency lock, found ${mediabunnyVersion}`);
}
copyRequired(
  join(mediabunnyRoot, "dist", "bundles", "mediabunny.min.mjs"),
  join(vendor, "mediabunny.js"),
);
copyRequired(join(mediabunnyRoot, "LICENSE"), join(vendor, "mediabunny.LICENSE"));
// geotiff is lock-controlled as bundled-self-hosted too (consumer task W08):
// the exact integrity-verified 3.0.5 browser bundle is vendored with its code
// unchanged (only the dangling source-map comment is dropped),
// wrapped by a tiny generated ESM shim that re-exports the UMD globals.
const geotiffRoot = join(root, "node_modules", "geotiff");
const geotiffVersion = JSON.parse(readRequired(join(geotiffRoot, "package.json"))).version;
if (geotiffVersion !== "3.0.5") {
  throw new Error(`geotiff must be 3.0.5 per the dependency lock, found ${geotiffVersion}`);
}
const geotiffUmdPath = join(vendor, "geotiff.umd.js");
copyVendoredScript(join(geotiffRoot, "dist-browser", "geotiff.js"), geotiffUmdPath);
copyRequired(join(geotiffRoot, "LICENSE"), join(vendor, "geotiff.LICENSE"));
writeFileSync(
  join(vendor, "geotiff.js"),
  `${[
    "// Generated by scripts/prepare-dist.mjs -- do not edit.",
    "// ESM wrapper over the vendored geotiff@3.0.5 UMD bundle.",
    'import "./geotiff.umd.js";',
    // The namespace binding must not be named `GeoTIFF`: the destructured
    // `GeoTIFF` class export below would redeclare it (a SyntaxError).
    "const geotiff = globalThis.GeoTIFF;",
    "if (geotiff === undefined) {",
    '  throw new Error("vendored geotiff.umd.js did not populate globalThis.GeoTIFF");',
    "}",
    "export default geotiff;",
    "export const {",
    "  BaseClient,",
    "  BaseDecoder,",
    "  BaseResponse,",
    "  GeoTIFF,",
    "  GeoTIFFImage,",
    "  ImageFileDirectory,",
    "  MultiGeoTIFF,",
    "  Pool,",
    "  addDecoder,",
    "  fromArrayBuffer,",
    "  fromBlob,",
    "  fromCustomClient,",
    "  fromFile,",
    "  fromUrl,",
    "  fromUrls,",
    "  getDecoder,",
    "  globals,",
    "  registerTag,",
    "  rgb,",
    "  setLogger,",
    "  writeArrayBuffer,",
    "} = geotiff;",
    "",
  ].join("\n")}`,
);
for (const file of readdirSync(dist)) {
  if (!file.endsWith(".js")) continue;
  const path = join(dist, file);
  const source = readFileSync(path, "utf8");
  const rewritten = source
    .replaceAll("from \"ktx-parse\"", "from \"./vendor/ktx-parse.js\"")
    .replaceAll("import(\"mediabunny\")", "import(\"./vendor/mediabunny.js\")")
    .replaceAll("import(\"geotiff\")", "import(\"./vendor/geotiff.js\")");
  if (/from\s+["']ktx-parse["']/u.test(rewritten)) {
    throw new Error(`dist/${file} still imports the bare ktx-parse specifier`);
  }
  if (/import\(\s*["']mediabunny["']\s*\)/u.test(rewritten)) {
    throw new Error(`dist/${file} still imports the bare mediabunny specifier`);
  }
  if (
    /import\(\s*["']geotiff["']\s*\)/u.test(rewritten) ||
    /from\s+["']geotiff["']/u.test(rewritten) ||
    /import\s+["']geotiff["']/u.test(rewritten)
  ) {
    throw new Error(`dist/${file} still imports the bare geotiff specifier`);
  }
  if (rewritten !== source) writeFileSync(path, rewritten);
}

// Package asset manifest: SHA-256 of every emitted self-hosted third-party asset.
const assetManifest = [
  ["dist/vendor/ktx-parse.js", "ktx-parse@1.1.0"],
  ["dist/vendor/mediabunny.js", "mediabunny@1.58.0"],
  ["dist/vendor/geotiff.umd.js", "geotiff@3.0.5"],
  ["dist/vendor/geotiff.js", "geotiff@3.0.5"],
  ["assets/basis/basis_transcoder.js", "basis_universal@2.0.3"],
  ["assets/basis/basis_transcoder.wasm", "basis_universal@2.0.3"],
  ...["index.mjs","harfbuzz.js","harfbuzz.wasm"].map(file => ["assets/harfbuzz/" + file, "harfbuzzjs@1.6.0"]),
  ...["NotoSans","NotoSansArabic","NotoSansDevanagari"].map(font => ["assets/fonts/" + font + "-Regular.ttf", "noto-fonts@ffebf8c1ee449e544955a7e813c54f9b73848eac"]),
].map(([path, source]) => ({
  path,
  source,
  sha256: createHash("sha256").update(readFileSync(join(root, path))).digest("hex"),
}));
writeFileSync(
  join(dist, "asset-manifest.json"),
  `${JSON.stringify({ assets: assetManifest }, undefined, 2)}\n`,
);

function copyRequired(from, to) {
  if (!existsSync(from)) {
    throw new Error(`Missing required package source: ${from}`);
  }
  copyFileSync(from, to);
}

// Vendored bundles keep their code bytes but drop the trailing
// sourceMappingURL: the upstream .map files are not shipped, and a dangling
// reference makes consumer dev servers and devtools report missing maps.
function copyVendoredScript(from, to) {
  const text = readRequired(from);
  writeFileSync(to, text.replace(/\n\/\/# sourceMappingURL=[^\n]*\s*$/u, "\n"));
}

function readRequired(path) {
  if (!existsSync(path)) {
    throw new Error(`Missing required package source: ${path}`);
  }
  return readFileSync(path, "utf8");
}

for (const file of ["label-features", "label-declutter", "label-types", "label-diagnostics", "label-candidates", "label-cases", "label-plan", "label-mesh", "typography", "labels"]) {
  const declaration = readRequired(join(dist, file + ".d.ts")).replace(/from (["'])\.\/(scene|camera)\.js\1/g, 'from "./index.js"');
  writeFileSync(join(root, "types", file + ".d.ts"), declaration);
}
copyRequired(join(repoRoot, "docs", "parity", "label-case-contract.json"), join(root, "docs", "label-case-contract.json"));
