use super::*;

#[cfg(feature = "extension-module")]
#[pyfunction]
#[pyo3(signature = (
    model, roughness, width, height,
    ndf_only=false, g_only=false, dfg_only=false, spec_only=false, roughness_visualize=false,
    exposure=1.0, light_intensity=0.8, base_color=(0.5, 0.5, 0.5),
    clearcoat=0.0, clearcoat_roughness=0.0, sheen=0.0, sheen_tint=0.0, specular_tint=0.0,
    debug_dot_products=false,
    debug_lambert_only=false, debug_diffuse_only=false, debug_d=false, debug_spec_no_nl=false, debug_energy=false,
    debug_angle_sweep=false, debug_angle_component=2,
    debug_no_srgb=false, output_mode=1, metallic_override=0.0,
    mode=None, wi3_debug_mode=0, wi3_debug_roughness=0.0,
    sphere_sectors=64, sphere_stacks=32
))]
pub(crate) fn render_brdf_tile<'py>(
    py: Python<'py>,
    model: &str,
    roughness: f32,
    width: u32,
    height: u32,
    ndf_only: bool,
    g_only: bool,
    dfg_only: bool,
    spec_only: bool,
    roughness_visualize: bool,
    exposure: f32,
    light_intensity: f32,
    base_color: (f32, f32, f32),
    clearcoat: f32,
    clearcoat_roughness: f32,
    sheen: f32,
    sheen_tint: f32,
    specular_tint: f32,
    debug_dot_products: bool,
    debug_lambert_only: bool,
    debug_diffuse_only: bool,
    debug_d: bool,
    debug_spec_no_nl: bool,
    debug_energy: bool,
    debug_angle_sweep: bool,
    debug_angle_component: u32,
    debug_no_srgb: bool,
    output_mode: u32,
    metallic_override: f32,
    mode: Option<&str>,
    wi3_debug_mode: u32,
    wi3_debug_roughness: f32,
    sphere_sectors: u32,
    sphere_stacks: u32,
) -> PyResult<Bound<'py, PyArray3<u8>>> {
    render_brdf_tile_impl(
        py,
        model,
        roughness,
        width,
        height,
        ndf_only,
        g_only,
        dfg_only,
        spec_only,
        roughness_visualize,
        exposure,
        light_intensity,
        base_color,
        clearcoat,
        clearcoat_roughness,
        sheen,
        sheen_tint,
        specular_tint,
        debug_dot_products,
        debug_lambert_only,
        debug_diffuse_only,
        debug_d,
        debug_spec_no_nl,
        debug_energy,
        debug_angle_sweep,
        debug_angle_component,
        debug_no_srgb,
        output_mode,
        metallic_override,
        mode,
        wi3_debug_mode,
        wi3_debug_roughness,
        sphere_sectors,
        sphere_stacks,
        None,
        0,
    )
}

#[cfg(feature = "extension-module")]
#[pyfunction]
#[pyo3(signature = (
    model, roughness, width, height,
    ndf_only=false, g_only=false, dfg_only=false, spec_only=false, roughness_visualize=false,
    exposure=1.0, light_intensity=0.8, base_color=(0.5, 0.5, 0.5),
    clearcoat=0.0, clearcoat_roughness=0.0, sheen=0.0, sheen_tint=0.0, specular_tint=0.0,
    debug_dot_products=false,
    debug_lambert_only=false, debug_diffuse_only=false, debug_d=false, debug_spec_no_nl=false, debug_energy=false,
    debug_angle_sweep=false, debug_angle_component=2,
    debug_no_srgb=false, output_mode=1, metallic_override=0.0,
    mode=None, wi3_debug_mode=0, wi3_debug_roughness=0.0,
    sphere_sectors=64, sphere_stacks=32,
    light_dir=None, debug_kind=0
))]
pub(crate) fn render_brdf_tile_overrides<'py>(
    py: Python<'py>,
    model: &str,
    roughness: f32,
    width: u32,
    height: u32,
    ndf_only: bool,
    g_only: bool,
    dfg_only: bool,
    spec_only: bool,
    roughness_visualize: bool,
    exposure: f32,
    light_intensity: f32,
    base_color: (f32, f32, f32),
    clearcoat: f32,
    clearcoat_roughness: f32,
    sheen: f32,
    sheen_tint: f32,
    specular_tint: f32,
    debug_dot_products: bool,
    debug_lambert_only: bool,
    debug_diffuse_only: bool,
    debug_d: bool,
    debug_spec_no_nl: bool,
    debug_energy: bool,
    debug_angle_sweep: bool,
    debug_angle_component: u32,
    debug_no_srgb: bool,
    output_mode: u32,
    metallic_override: f32,
    mode: Option<&str>,
    wi3_debug_mode: u32,
    wi3_debug_roughness: f32,
    sphere_sectors: u32,
    sphere_stacks: u32,
    light_dir: Option<(f32, f32, f32)>,
    debug_kind: u32,
) -> PyResult<Bound<'py, PyArray3<u8>>> {
    render_brdf_tile_impl(
        py,
        model,
        roughness,
        width,
        height,
        ndf_only,
        g_only,
        dfg_only,
        spec_only,
        roughness_visualize,
        exposure,
        light_intensity,
        base_color,
        clearcoat,
        clearcoat_roughness,
        sheen,
        sheen_tint,
        specular_tint,
        debug_dot_products,
        debug_lambert_only,
        debug_diffuse_only,
        debug_d,
        debug_spec_no_nl,
        debug_energy,
        debug_angle_sweep,
        debug_angle_component,
        debug_no_srgb,
        output_mode,
        metallic_override,
        mode,
        wi3_debug_mode,
        wi3_debug_roughness,
        sphere_sectors,
        sphere_stacks,
        light_dir,
        debug_kind,
    )
}
