use anyhow::Result;

use super::params::BrdfTileOverrides;
use super::render::render_brdf_tile;
use super::request::BrdfTileRenderRequest;

/// Render a BRDF tile offscreen and return a tight RGBA8 buffer.
pub fn render_brdf_tile_offscreen(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    model_u32: u32,
    roughness: f32,
    width: u32,
    height: u32,
    ndf_only: bool,
    g_only: bool,
    dfg_only: bool,
    spec_only: bool,
    roughness_visualize: bool,
    exposure: f32,
    light_intensity: f32,
    base_color: [f32; 3],
    clearcoat: f32,
    clearcoat_roughness: f32,
    sheen: f32,
    sheen_tint: f32,
    specular_tint: f32,
    debug_dot_products: bool,
    debug_lambert_only: bool,
    debug_diffuse_only: bool,
    debug_d: bool,
    debug_spec_no_nl: bool,
    debug_energy: bool,
    debug_angle_sweep: bool,
    debug_angle_component: u32,
    debug_no_srgb: bool,
    output_mode: u32,
    metallic_override: f32,
    wi3_debug_mode: u32,
    wi3_debug_roughness: f32,
    sphere_sectors: u32,
    sphere_stacks: u32,
) -> Result<Vec<u8>> {
    render_brdf_tile_with_overrides(
        device,
        queue,
        model_u32,
        roughness,
        width,
        height,
        ndf_only,
        g_only,
        dfg_only,
        spec_only,
        roughness_visualize,
        exposure,
        light_intensity,
        base_color,
        clearcoat,
        clearcoat_roughness,
        sheen,
        sheen_tint,
        specular_tint,
        debug_dot_products,
        debug_lambert_only,
        debug_diffuse_only,
        debug_d,
        debug_spec_no_nl,
        debug_energy,
        debug_angle_sweep,
        debug_angle_component,
        debug_no_srgb,
        output_mode,
        metallic_override,
        wi3_debug_mode,
        wi3_debug_roughness,
        sphere_sectors,
        sphere_stacks,
        &BrdfTileOverrides::default(),
    )
}

pub fn render_brdf_tile_with_overrides(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    model_u32: u32,
    roughness: f32,
    width: u32,
    height: u32,
    ndf_only: bool,
    g_only: bool,
    dfg_only: bool,
    spec_only: bool,
    roughness_visualize: bool,
    exposure: f32,
    light_intensity: f32,
    base_color: [f32; 3],
    clearcoat: f32,
    clearcoat_roughness: f32,
    sheen: f32,
    sheen_tint: f32,
    specular_tint: f32,
    debug_dot_products: bool,
    debug_lambert_only: bool,
    debug_diffuse_only: bool,
    debug_d: bool,
    debug_spec_no_nl: bool,
    debug_energy: bool,
    debug_angle_sweep: bool,
    debug_angle_component: u32,
    debug_no_srgb: bool,
    output_mode: u32,
    metallic_override: f32,
    wi3_debug_mode: u32,
    wi3_debug_roughness: f32,
    sphere_sectors: u32,
    sphere_stacks: u32,
    overrides: &BrdfTileOverrides,
) -> Result<Vec<u8>> {
    render_brdf_tile(
        device,
        queue,
        BrdfTileRenderRequest {
            model_u32,
            roughness,
            width,
            height,
            ndf_only,
            g_only,
            dfg_only,
            spec_only,
            roughness_visualize,
            exposure,
            light_intensity,
            base_color,
            clearcoat,
            clearcoat_roughness,
            sheen,
            sheen_tint,
            specular_tint,
            debug_dot_products,
            debug_lambert_only,
            debug_diffuse_only,
            debug_d,
            debug_spec_no_nl,
            debug_energy,
            debug_angle_sweep,
            debug_angle_component,
            debug_no_srgb,
            output_mode,
            metallic_override,
            wi3_debug_mode,
            wi3_debug_roughness,
            sphere_sectors,
            sphere_stacks,
            overrides: *overrides,
        },
    )
}
